import { library } from "@fortawesome/fontawesome-svg-core"

import {
  faHeart,
  faTicket,
  faGift,
  faMoneyCheckDollar,
  faCircleCheck,
  faPlus,
  faMinus,
  faHouse,
  faQuestion,
  faLayerGroup,
  faStore,
  faUser,
  faListUl,
  faGrid,
  faCircle3,
  faCircleInfo,
  faXmark,
  faChevronUp,
  faChevronDown,
  faMagnifyingGlass as fasMagnifyingGlass,
  faCartShopping as fasCartShopping,
  faBolt,
  faEllipsis,
  faArrowRightFromBracket,
  faBarsFilter,
  faArrowRight,
  faClone,
  faBadgeCheck,
  faBadge,
  faCirclePlus,
  faCircleBolt,
  faForward,
  faArrowLeft,
  faFilter,
  faAngleDown,
  faBarsSort,
  faTrashCan,
  faCircle1,
  faCircle2,
  faCheck,
  faX,
  faChevronRight,
} from "@fortawesome/pro-solid-svg-icons"

import {
  faHeart as farHeart,
  faShieldExclamation,
  faSquareArrowUpRight,
  faStar,
  faHourglass,
  faChartLineUp,
  faCartShopping,
  faSend,
  faMoneyBills,
  faArrowsRotate,
  faMagnifyingGlass,
  faFilters,
  faCircleInfo as farCircleInfo,
  faArrowUpRightFromSquare,
  faLocationDot,
  faGlobe,
} from "@fortawesome/pro-regular-svg-icons"

import {
  faGithub,
  faTelegram,
  faDiscord,
  faTwitter,
  faFacebook,
  faYoutube,
  faTwitch,
} from "@fortawesome/free-brands-svg-icons"

import { faTrash } from "@fortawesome/pro-light-svg-icons"

import { faSpinner } from "@fortawesome/pro-duotone-svg-icons"

// import {} from "@fortawesome/pro-thin-svg-icons"
// import {} from "@fortawesome/sharp-light-svg-icons"
// import {} from "@fortawesome/sharp-regular-svg-icons"
// import {} from "@fortawesome/sharp-solid-svg-icons"

export const initializeFAIcons = () => {
  library.add(
    faCircle3,
    faArrowLeft,
    faCircleCheck,
    faCartShopping,
    faSend,
    faTicket,
    faMoneyCheckDollar,
    faGift,
    faHourglass,
    faChartLineUp,
    faHeart,
    farHeart,
    faShieldExclamation,
    faStar,
    faSquareArrowUpRight,
    faMoneyBills,
    faTrash,
    faArrowsRotate,
    faTrashCan,
    faMagnifyingGlass,
    faCircleInfo,
    faPlus,
    faBarsSort,
    faMinus,
    faFilters,
    faHouse,
    faQuestion,
    faLayerGroup,
    faStore,
    faUser,
    faListUl,
    faGrid,
    faXmark,
    faChevronUp,
    faChevronDown,
    farCircleInfo,
    fasMagnifyingGlass,
    fasCartShopping,
    faBolt,
    faEllipsis,
    faArrowRightFromBracket,
    faBarsFilter,
    faArrowRight,
    faClone,
    faBadgeCheck,
    faArrowUpRightFromSquare,
    faCirclePlus,
    faCircleBolt,
    faLocationDot,
    faGlobe,
    faGithub,
    faTelegram,
    faDiscord,
    faTwitter,
    faFacebook,
    faYoutube,
    faTwitch,
    faBadge,
    faFilter,
    faAngleDown,
    faCircle1,
    faCircle2,
    faSpinner,
    faCheck,
    faForward,
    faBadge,
    faX,
    faChevronRight,
  )
}
